def fileContents
pipeline {

    agent any
    
    //triggers {
    //    cron 'H/2 * * * *'
    //}


    parameters {
        choice choices: ['INT', 'STR'], name: 'DATATYPE'
        string defaultValue: 'dwsahu-VirtualBox', description: 'My Hostname', name: 'HOSTNAME'
        booleanParam description: 'pull mongo db image', name: 'mongo_db_image'
        booleanParam description: 'pull ubuntu image', name: 'mongo_ubuntu_image'
    }
    
    environment{
        GIT_REPO_PERSONAL = 'https://github.com/dwarika1988/my_programs.git'
        GIT_CRED_ID = 'dps_cred'
        //GIT_PAT = credentials('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')
    }

    
    stages {
        
        stage (Stage1){
            
            steps{
                script{
                    sh """
                        hostname
                    """
                }
            }
        }
        
        stage (ReadFile){
            when { expression { env.BRANCH_NAME == 'main' } }
            steps{
                script{
                    echo "${env.GIT_BRANCH}"
                    fileContents=readFile 'jenkins.txt'
                }
            }
        }
        
        
        stage (PrintReadContent){
            
            options {
                timeout(time:2, unit:'MINUTES')
            }
        
            steps {
                script{
                    sh """
                       #sleep  1.00m
		       	echo "hello PrintReadContent"
                        echo "$fileContents"
                    """
                }
            }
        }
        
        stage ('writeFile'){
			steps{
				writeFile file:'output_1.txt',text:'''line
				line2
				line3'''
			}	
		}
        stage (ReadWroteFile){
            steps{
                sh"""
                    cat output_1.txt
                """
            }
        }
        
        
        /*
        stage ('RunTime-Input'){
            steps {
                scripts{
                    input (message:'hello worlds', ok:'submit')
                }
            }
        }
        */
        
        stage('try-except'){
		    steps{
		        script{
		            try{
		                //sh'hostname'
		                sh'hello'
		            }catch (err){
		                echo "Caught:${err}"
		                currentBuild.result = 'UNSTABLE'
		            }
		            step([$class:'Mailer',recipients:'dwsahu@cisco.com'])
		        }
		    }
		}
        stage (FileHandling_Bash){
            steps{
                sh"""
                    
                    if [ -f "jenkins_training.txt" ];
                    then
                        echo "file_exists"
                    else
                        touch "jenkins_training.txt"
                    fi
                        
                """
            }
        }
        
        stage (Choice){
            steps{
                sh'''
                    datatype=${DATATYPE}
                    echo "${DATATYPE}"
                    a=10
                    b=abc
                    if [ ${datatype} = "INT" ];
                    then
                        echo "$a"
                    elif [ ${datatype} = "STR" ];
                    then
                        echo "$b"
                    fi
                '''
            }
        }
        
        stage ('String-Data'){
            steps{
                sh'''
                    echo "$HOSTNAME"
                '''
            }
        }
        
        stage ('MongoDB_Image'){
            when { 
                expression { params.mongo_db_image == true } 

            }
            steps{
                sh'''
                    #bash docker_mongo.sh
                    echo "mongodb"
                    #echo "BA@Ba20130781" | sudo -S docker pull mongo
                '''
            }
        }
        
        stage ('Ubuntu_Image'){
            when { expression { params.mongo_ubuntu_image == true } }
            steps{
                sh'''
                    #bash docker_ubuntu.sh
                    echo "ubuntu"
                    #echo "BA@Ba20130781" | sudo -S docker pull ubuntu
                '''
            }
        }
        
        stage ('FileHandling'){
            steps{
                script{
                    def filePath = '/var/lib/jenkins/workspace/MyJOb/Jenkins_testing.txt'
                    def desiresPermissions = 'u+rwx'
                    
                    if(fileExists(filePath)){
                        echo "file $filePath exists"
                        
                        def fileContent = readFile(filePath)
                        //echo "$fileContent"
                    } else {
                        def fileContent
                        fileContent ="\nhello and how are you"
                        writeFile(file: filePath, text:fileContent)
                        sh "chmod ${desiresPermissions} ${filePath}"
                        
                    }
                }
            }
        }
        
        stage (DisplayName){
            steps{
                script{
                    def displayBuildName = currentBuild.displayName
                    echo "display name of the current build is $displayBuildName"
                }
            }
        }
        
        stage('AnyOF Job Name Validation') {
            when {
                anyOf {
                    expression {
                        currentBuild.displayName ==~ /^[0-9]+$/
                    }
                    
                    expression {
                        def result = sh(script: '''
                            #!/bin/bash
                            if [ "$BUILD_NUMBER" -gt "10" ]; then
                                exit 0  # Condition is true
                            else
                                exit 1  # Condition is fals
                            fi
                        ''', returnStatus: true)
                        return result == 0
                    }
                }
            }
            steps {
                script {
                    def jobName = currentBuild.fullProjectName
                    echo "Job name is valid: $jobName"
                }
            }
        }
        
        stage('allOF Job Name Validation') {
            when {
                allOf {
                    expression {
                        def result = sh(script: '''
                            #!/bin/bash
                            a=10
                            b=11
                            if [ $a -le $b ]; then
                                exit 0  # Condition is true
                            else
                                exit 1  # Condition is false
                            fi
                        ''', returnStatus: true)
                        return result == 0
                    }
                    
                    expression {
                        def result = sh(script: '''
                            #!/bin/bash
                            if [ "$BUILD_NUMBER" -le "10" ]; then
                                exit 0  # Condition is true
                            else
                                exit 1  # Condition is fals
                            fi
                        ''', returnStatus: true)
                        return result == 0
                    }
                }
            }
            steps {
                script {
                    def jobName = currentBuild.fullProjectName
                    echo "Job name is valid: $jobName"
                }
            }
        }
        
        /*
        stage ('GIT_PULL_BASH'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dps_cred', passwordVariable: 'REPO_PWD', usernameVariable: 'REPO_LOGIN')]){
                    sh'''
                        git clone https://$REPO_LOGIN:$(echo -n $REPO_PWD| hexdump -v -e '"x" 1/1 "%02X"' | tr x %)@github.com/dwarika1988/my_programs.git
                    '''
                }
            }
        }
        */
        
        
        stage ('GIT_CHECKOUT'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: GIT_REPO_PERSONAL,credentialsId:GIT_CRED_ID]]])
            }
        }
        
        stage ('create and checkout to new branch'){
            steps{
                script{
                    def gitBranchName = 'jenkins-test'
				    sh "git config user.name 'dwarika1988'"
		            sh "git config user.email 'dwarika1988@gmail.com'"
		        
		            def repoDirectory = 'my_programs'
		            def repoAlreadyCloned = fileExists(repoDirectory)
		        
		            if (!repoAlreadyCloned) {
		              sh "git clone -b $gitBranchName $GIT_REPO_PERSONAL $repoDirectory"
		            }
		    
		            def branchExists = sh(script: "git show-ref --verify --quiet refs/heads/$gitBranchName", returnStatus: true) == 0
		        
		            if (!branchExists) {
		               sh "git checkout -b $gitBranchName"
		            }
                }
            }
        }
        
        stage ('make changes and git commit'){
            steps{
                script{
                    def gitBranchName = 'jenkins-test'  // Replace with your branch name

        
                            // Define the Git credentials ID configured in Jenkins
                            def gitCredentialsId = 'dps_cred'
        
                            // Set Git user name and email
                            sh "git config user.name 'dwarika1988'"
                            sh "git config user.email 'dwarika1988@gmail.com'"
        
                            // Make and commit changes
                            sh "echo 'new changes' > git-checkout.txt"
                            sh "git add . && git commit -m 'create branch and commit via Jenkins Pipeline'"
        
                            // Push the changes with the provided username and password
                            withCredentials([usernamePassword(credentialsId: gitCredentialsId, passwordVariable: 'DPSgit@2023', usernameVariable: 'dwarika1988')]) {
                              sh "git push origin $gitBranchName"
                            }
                }
            }
        }
    }
}

